import { store } from '../core/store.js';
import { applyTheme } from '../core/theme.js';
import { startRouter, go, getPage } from '../core/router.js';
import { homePage } from '../pages/home.js';
import { settingsPage, bindSettings } from '../pages/settings.js';
import { simplePage } from '../pages/other.js';
import { icons } from './icons.js';

const labels=[['home','Home'],['games','Games'],['ai','AI'],['proxy','Proxy'],['phone','Phone'],['spoof','Spoof'],['utilities','Utilities'],['settings','Settings']];
export class AppUI {
  constructor(){this.app=document.querySelector('#app');this.toastStack=document.createElement('div');this.toastStack.className='toast-stack';document.body.appendChild(this.toastStack);this.clockTimer=null}
  toast(msg){const e=document.createElement('div');e.className='toast';e.textContent=msg;this.toastStack.appendChild(e);setTimeout(()=>e.remove(),2200)}
  render(page=getPage()){document.documentElement.style.setProperty('--ui-scale',store.get().uiScale);const online=navigator.onLine;this.app.innerHTML=`<div class="app-shell"><header class="topbar glass"><div class="brand"><div class="brand-mark"></div><div><div class="brand-name">NEXUS</div><div class="brand-sub">PERSONAL WEB OS</div></div></div><nav class="nav">${labels.map(([id,label])=>`<button class="nav-btn ${page===id?'active':''}" data-page="${id}">${label}</button>`).join('')}</nav><div class="top-actions"><div class="status-pill ${online?'':'offline'}"><span class="status-dot"></span><span class="status-text">${online?'CONNECTED':'OFFLINE'}</span></div><div class="clock-pill"><span class="clock-text clock-main" id="clock">--:--</span><span class="clock-date" id="date">---</span></div><button class="icon-btn" title="Console" id="console-btn">${icons.console}</button><button class="icon-btn" title="Settings" id="settings-btn">${icons.settings}</button></div></header><main class="app-main" id="main-content"></main></div><div class="hud-layer" id="hud-layer"></div><div class="modal-backdrop" id="console-modal"><section class="modal glass"><div class="modal-head"><div><h3>GAME CONSOLE</h3><div class="muted" style="font-size:9px;margin-top:4px">Same-origin/local games only for live execution context access.</div></div><button class="icon-btn" id="console-close">×</button></div><div class="modal-body"><div class="console"><div class="console-log" id="console-log"></div><div class="console-input"><input id="console-input" placeholder="type a command… (try help)"/><button id="console-send">EXEC</button></div></div></div></section></div>`;
    const main=this.app.querySelector('#main-content');const pages={home:homePage,games:()=>simplePage('games'),ai:()=>simplePage('ai'),proxy:()=>simplePage('proxy'),phone:()=>simplePage('phone'),spoof:()=>simplePage('spoof'),utilities:()=>simplePage('utilities'),settings:settingsPage};main.innerHTML=pages[page]();this.bindNav();this.updateClock();if(!this.clockTimer)this.clockTimer=setInterval(()=>this.updateClock(),1000);this.app.querySelector('#settings-btn')?.addEventListener('click',()=>go('settings'));this.app.querySelector('#console-btn')?.addEventListener('click',()=>this.openConsole(page));this.bindConsole();if(page==='settings')bindSettings({rerender:()=>this.render(getPage()),toast:m=>this.toast(m)});document.dispatchEvent(new CustomEvent('nexus:app-render'));}
  bindNav(){document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.page)))}
  updateClock(){const now=new Date();const c=document.querySelector('#clock'),d=document.querySelector('#date');if(!c)return;c.textContent=now.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'});d.textContent=now.toLocaleDateString([], {month:'short',day:'2-digit'}).toUpperCase()}
  openConsole(page){const m=document.querySelector('#console-modal');m?.classList.add('open');const log=document.querySelector('#console-log');if(!log)return;log.innerHTML='';if(page!=='games'){this.log('Console is available for games only. Open a game first.','warn')}else{this.log('No game is mounted yet. The console is ready for a same-origin/local game context.','info')}document.querySelector('#console-input')?.focus()}
  bindConsole(){document.querySelector('#console-close')?.addEventListener('click',()=>document.querySelector('#console-modal')?.classList.remove('open'));const send=()=>{const input=document.querySelector('#console-input');const value=input?.value.trim();if(!value)return;this.log('> '+value,'cmd');if(value==='help')this.log('Commands: help, clear, status','info');else if(value==='clear')document.querySelector('#console-log').innerHTML='';else if(value==='status')this.log('NEXUS console: shell=ready, gameContext=not-mounted','info');else this.log(`Unknown command: ${value}`,'error');input.value='';input.focus()};document.querySelector('#console-send')?.addEventListener('click',send);document.querySelector('#console-input')?.addEventListener('keydown',e=>{if(e.key==='Enter')send()})}
  log(text,type='info'){const el=document.createElement('div');el.className='line '+type;el.textContent=text;const log=document.querySelector('#console-log');log?.appendChild(el);log?.scrollTo(0,log.scrollHeight)}
}
