import { store } from '../core/store.js';
import { applyTheme } from '../core/theme.js';
import { startRouter, go, getPage } from '../core/router.js';
import { homePage } from '../pages/home.js';
import { settingsPage, bindSettings } from '../pages/settings.js';
import { simplePage, bindSimple, applySpoof } from '../pages/other.js';
import { gamesPage, bindGames } from '../pages/games.js';
import { utilitiesPage, bindUtilities } from '../pages/utilities.js';
import { aiPage, bindAI } from '../pages/ai.js';
import { gameManager } from '../games/manager.js';
import { icons } from './icons.js';
import { getConnectionState } from '../core/connection.js';

const labels=[['home','Home'],['games','Games'],['ai','AI'],['proxy','Proxy'],['phone','Phone'],['spoof','Spoof']];
export class AppUI {
 constructor(){this.app=document.querySelector('#app');this.toastStack=document.createElement('div');this.toastStack.className='toast-stack';document.body.appendChild(this.toastStack);this.clockTimer=null;this.consoleHistory=[];this.consoleIndex=0;this.maxConsole=false;this.settingsOpen=false;this.installGameEvents();applySpoof();}
 toast(msg){const e=document.createElement('div');e.className='toast';e.textContent=msg;this.toastStack.appendChild(e);setTimeout(()=>e.remove(),2200)}
 render(page=getPage()){
  const st=store.get();document.documentElement.style.setProperty('--ui-scale',st.uiScale);document.documentElement.style.setProperty('--glow-strength',st.glow);document.body.dataset.aspect=st.aspectRatio;
  const c=getConnectionState();
  this.app.innerHTML=`<div class="app-shell"><header class="topbar glass"><div class="brand"><div class="brand-mark"></div><div><div class="brand-name">NEXUS</div><div class="brand-sub">PERSONAL WEB OS</div></div></div><nav class="nav">${labels.map(([id,label])=>`<button class="nav-btn ${page===id?'active':''}" data-page="${id}">${label}</button>`).join('')}<button class="nav-btn utilities-link ${page==='utilities'?'active':''}" data-page="utilities">Utilities</button></nav><div class="top-actions"><button class="status-pill" id="connection-btn"><span class="status-dot"></span><span class="status-text">● ONLINE</span></button><div class="clock-pill"><span class="clock-text clock-main" id="clock">--:--</span><span class="clock-date" id="date">---</span></div><button class="icon-btn" title="Game Console" id="console-btn">${icons.console}</button><button class="icon-btn" title="Settings" id="settings-btn">${icons.settings}</button></div></header><main class="app-main" id="main-content"></main></div><div class="hud-layer" id="hud-layer"></div><div class="connection-panel glass" id="connection-panel"><div class="section-top"><h3>Connection Status</h3><button class="icon-btn" id="connection-close">×</button></div><div class="status-detail"><div><span>APPLICATION</span><b>● ONLINE</b></div><div><span>NETWORK</span><b>${c.network==='AVAILABLE'?'● AVAILABLE':'○ UNAVAILABLE'}</b></div><div><span>BACKEND</span><b>○ ${c.backend}</b></div><div><span>AI SERVICES</span><b>○ ${c.ai}</b></div><div><span>SPOTIFY</span><b>○ ${c.spotify}</b></div></div></div><div class="modal-backdrop" id="settings-modal"><section class="modal settings-modal glass"><div class="modal-head"><div><h3>SETTINGS</h3><div class="muted modal-sub">System configuration · changes apply immediately</div></div><button class="icon-btn" id="settings-close">×</button></div><div class="modal-body" id="settings-panel">${settingsPage()}</div></section></div><div class="modal-backdrop" id="console-modal"><section class="modal console-modal glass"><div class="modal-head"><div><h3>GAME CONSOLE</h3><div class="muted modal-sub">Attached to local/same-origin game context.</div></div><div class="modal-actions"><button class="icon-btn" id="console-hide-output">≋</button><button class="icon-btn" id="console-min">−</button><button class="icon-btn" id="console-max">□</button><button class="icon-btn" id="console-close">×</button></div></div><div class="modal-body"><div class="console"><div class="console-log" id="console-log"></div><div class="console-input"><input id="console-input" autocomplete="off" placeholder="type a command… (help)"><button id="console-send">EXEC</button></div></div></div></section></div>`;
  const main=this.app.querySelector('#main-content');
  if(page==='home')main.innerHTML=homePage();else if(page==='games')main.innerHTML=gamesPage();else if(page==='ai')main.innerHTML=aiPage();else if(page==='utilities')main.innerHTML=utilitiesPage();else main.innerHTML=simplePage(page);
  this.bindNav();this.updateClock();if(!this.clockTimer)this.clockTimer=setInterval(()=>this.updateClock(),1000);
  this.app.querySelector('#settings-btn')?.addEventListener('click',()=>this.openSettings());
  this.app.querySelector('#connection-btn')?.addEventListener('click',()=>document.querySelector('#connection-panel')?.classList.toggle('open'));
  document.querySelector('#connection-close')?.addEventListener('click',()=>document.querySelector('#connection-panel')?.classList.remove('open'));
  this.app.querySelector('#console-btn')?.addEventListener('click',()=>this.openConsole(page));
  document.querySelector('#settings-close')?.addEventListener('click',()=>this.closeSettings());
  document.querySelector('#settings-modal')?.addEventListener('click',e=>{if(e.target.id==='settings-modal')this.closeSettings()});
  this.bindConsole();bindSettings({rerender:()=>this.render(getPage()),toast:m=>this.toast(m)});
  if(page==='games')bindGames({openConsole:()=>this.openConsole('games'),toast:m=>this.toast(m)});
  if(page==='ai')bindAI({toast:m=>this.toast(m)});
  if(page==='utilities')bindUtilities({toast:m=>this.toast(m),openSettings:section=>this.openSettings(section)});
  bindSimple(page,{toast:m=>this.toast(m)});
  document.querySelector('#home-settings')?.addEventListener('click',()=>this.openSettings());
  document.dispatchEvent(new CustomEvent('nexus:app-render'));
 }
 bindNav(){this.app.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.page)))}
 updateClock(){const now=new Date(),c=document.querySelector('#clock'),d=document.querySelector('#date');if(!c)return;c.textContent=now.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'});if(d)d.textContent=now.toLocaleDateString([], {month:'short',day:'2-digit'}).toUpperCase()}
 openSettings(section){const modal=document.querySelector('#settings-modal');if(!modal)return;modal.classList.add('open');this.settingsOpen=true;if(section){document.querySelector(`[data-settings-section="${section}"]`)?.click()}}
 closeSettings(){document.querySelector('#settings-modal')?.classList.remove('open');this.settingsOpen=false}
 openConsole(page){const modal=document.querySelector('#console-modal');if(!modal)return;modal.classList.add('open');modal.classList.remove('minimized');const log=document.querySelector('#console-log');if(log&&!log.childElementCount){if(page!=='games')this.log('Console is available for games only. Open a game first.','warn');else if(gameManager.getActive())this.log(`Attached: ${gameManager.getActive().name}`,'info');else this.log('No game is mounted. Launch a local game first.','warn')}document.querySelector('#console-input')?.focus()}
 bindConsole(){document.querySelector('#console-close')?.addEventListener('click',()=>document.querySelector('#console-modal')?.classList.remove('open'));document.querySelector('#console-min')?.addEventListener('click',()=>document.querySelector('#console-modal')?.classList.toggle('minimized'));document.querySelector('#console-max')?.addEventListener('click',()=>{this.maxConsole=!this.maxConsole;document.querySelector('#console-modal .modal')?.classList.toggle('maximized',this.maxConsole)});const send=()=>{const input=document.querySelector('#console-input'),value=input?.value.trim();if(!value)return;this.consoleHistory.push(value);this.consoleIndex=this.consoleHistory.length;this.log('> '+value,'cmd');this.executeCommand(value);input.value='';input.focus()};document.querySelector('#console-send')?.addEventListener('click',send);document.querySelector('#console-input')?.addEventListener('keydown',e=>{if(e.key==='Enter')send();else if(e.key==='ArrowUp'){this.consoleIndex=Math.max(0,this.consoleIndex-1);e.target.value=this.consoleHistory[this.consoleIndex]||''}else if(e.key==='ArrowDown'){this.consoleIndex=Math.min(this.consoleHistory.length,this.consoleIndex+1);e.target.value=this.consoleHistory[this.consoleIndex]||''}})}
 executeCommand(value){const game=gameManager.getActive();if(value==='help'){this.log('Commands: help, clear, status, context, eval <expression>','info');return}if(value==='clear'){const l=document.querySelector('#console-log');if(l)l.innerHTML='';return}if(value==='status'){this.log(`application=online | page=${getPage()} | game=${game?game.name:'none'}`,'info');return}if(value==='context'){this.log(game?JSON.stringify({id:game.id,name:game.name},null,2):'No active game context.','info');return}if(value.startsWith('eval ')){if(!game){this.log('No active game context.','warn');return}try{const r=gameManager.evaluate(value.slice(5));this.log(typeof r==='undefined'?'undefined':String(r),'info')}catch(err){this.log(err.message||String(err),'error')}return}this.log(`Unknown command: ${value}`,'error')}
 log(text,type='info'){const log=document.querySelector('#console-log');if(!log)return;const el=document.createElement('div');el.className='line '+type;el.textContent=text;log.appendChild(el);log.scrollTop=log.scrollHeight}
 installGameEvents(){window.addEventListener('message',e=>{if(e.data?.source!=='nexus-game-console')return;const active=gameManager.getActive();if(active&&e.data.gameId!==active.id)return;this.log(`[game:${e.data.level}] ${e.data.message}`,e.data.level==='error'?'error':e.data.level==='warn'?'warn':'info')})}
}
