import {aiStore} from '../ai/store.js';
import {providerCatalog} from '../ai/providers.js';

function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\'':'&#39;','"':'&quot;'}[c]))}
export function aiPage(){
 const st=aiStore.get();
 return `<div class="page ai-page"><div class="page-title"><div><h2>AI</h2><p>Provider-neutral workspace. No provider is treated as configured until an explicit connection exists.</p></div><span class="code-pill">${st.chats.length} CHATS</span></div>
 <div class="ai-layout"><aside class="glass ai-sidebar"><div class="section-top"><h3>Conversations</h3><button class="icon-btn" id="new-chat">+</button></div><div id="chat-list" class="chat-list"></div><div class="ai-sidebar-footer"><label class="muted">Agent<select id="agent-select"><option>General Assistant</option><option>Coding Agent</option><option>Research Agent</option><option>Creative Agent</option><option>Debugging Agent</option><option>Custom</option></select></label></div></aside>
 <section class="glass ai-main"><div class="ai-toolbar"><div><b id="ai-title">New chat</b><span class="muted" id="ai-provider-label">${esc(providerCatalog[st.provider]?.name||st.provider)} · ${st.model?esc(st.model):'model not configured'}</span></div><button class="ghost-btn" id="ai-settings">Provider settings</button></div><div id="chat-messages" class="chat-messages"><div class="empty"><div class="empty-icon">✦</div><strong>Awaiting a provider</strong><span>Connect a provider below, then send a message. The interface will never synthesize fake AI replies.</span></div></div><div class="chat-compose"><textarea id="chat-input" rows="2" placeholder="Message the selected provider…"></textarea><button class="primary-btn" id="send-chat">SEND</button></div></section>
 <section class="glass section-card ai-config"><div class="section-top"><h3>Provider Architecture</h3><span class="code-pill">CLIENT SHELL</span></div><div class="control-grid"><div class="control"><label>Provider</label><select id="provider-select">${Object.entries(providerCatalog).map(([id,p])=>`<option value="${id}" ${st.provider===id?'selected':''}>${p.name}</option>`).join('')}</select></div><div class="control"><label>Model</label><input id="provider-model" type="text" placeholder="e.g. model-id" value="${esc(st.model)}"></div><div class="control"><label>Endpoint</label><input id="provider-endpoint" type="text" placeholder="Optional backend URL" value="${esc(st.endpoint)}"><small>Use a backend you control when credentials must stay secret.</small></div><div class="control"><label>Secret configured <button class="switch ${st.secretConfigured?'on':''}" id="secret-toggle"></button></label><small>This flag records configuration only. It does not store or expose a secret.</small></div></div><div class="notice" style="margin-top:12px">GitHub Pages can host this shell, but it should not contain private provider API secrets. A serverless/backend adapter can implement the actual provider call later without changing the chat UI.</div></section></div></div>`;
}

export function bindAI(){
 const root=document.querySelector('.ai-page');if(!root)return;let current=aiStore.get().chats[0]?.id||null;
 const list=root.querySelector('#chat-list'),messages=root.querySelector('#chat-messages');
 function renderList(){const chats=aiStore.get().chats;list.innerHTML=chats.length?chats.map(c=>`<button class="chat-row ${c.id===current?'active':''}" data-chat="${c.id}"><span>${esc(c.title)}</span><small>${c.messages.length}</small></button>`).join(''):'<div class="empty">No saved chats</div>';list.querySelectorAll('[data-chat]').forEach(b=>b.addEventListener('click',()=>{current=b.dataset.chat;renderChat()}))}
 function renderChat(){const chat=aiStore.get().chats.find(c=>c.id===current);if(!chat){messages.innerHTML='<div class="empty"><strong>New chat</strong><span>Send your first message after a provider is configured.</span></div>';root.querySelector('#ai-title').textContent='New chat';return}root.querySelector('#ai-title').textContent=chat.title;messages.innerHTML=chat.messages.map(m=>`<div class="chat-message ${m.role}"><div class="chat-role">${m.role.toUpperCase()}</div><div class="chat-bubble">${esc(m.content)}</div></div>`).join('');messages.scrollTop=messages.scrollHeight}
 function newChat(){const chat={id:crypto.randomUUID(),title:'New chat',createdAt:new Date().toISOString(),messages:[]};aiStore.addChat(chat);current=chat.id;renderList();renderChat()}
 root.querySelector('#new-chat')?.addEventListener('click',newChat);
 root.querySelector('#send-chat')?.addEventListener('click',()=>{const input=root.querySelector('#chat-input'),content=input.value.trim();if(!content)return;const st=aiStore.get();if(!st.secretConfigured||!st.model){root.querySelector('#chat-messages').insertAdjacentHTML('beforeend','<div class="chat-message system"><div class="chat-role">SYSTEM</div><div class="chat-bubble">AI provider not configured. No request was sent.</div></div>');return}let chat=st.chats.find(c=>c.id===current);if(!chat){newChat();chat=aiStore.get().chats.find(c=>c.id===current)}chat.messages.push({role:'user',content,at:new Date().toISOString()});chat.title=chat.title==='New chat'?content.slice(0,32):chat.title;aiStore.updateChats(st.chats);input.value='';renderList();renderChat()});
 root.querySelector('#provider-select')?.addEventListener('change',e=>{aiStore.set({provider:e.target.value});root.querySelector('#ai-provider-label').textContent=providerCatalog[e.target.value].name+' · '+(aiStore.get().model||'model not configured')});
 root.querySelector('#provider-model')?.addEventListener('change',e=>{aiStore.set({model:e.target.value});root.querySelector('#ai-provider-label').textContent=providerCatalog[aiStore.get().provider].name+' · '+(e.target.value||'model not configured')});
 root.querySelector('#provider-endpoint')?.addEventListener('change',e=>aiStore.set({endpoint:e.target.value}));
 root.querySelector('#secret-toggle')?.addEventListener('click',()=>{aiStore.set({secretConfigured:!aiStore.get().secretConfigured});root.querySelector('#secret-toggle').classList.toggle('on',aiStore.get().secretConfigured)});
 root.querySelector('#agent-select')?.addEventListener('change',e=>aiStore.set({agent:e.target.value}));
 root.querySelector('#ai-settings')?.addEventListener('click',()=>root.querySelector('.ai-config')?.scrollIntoView({behavior:'smooth'}));
 if(!current && aiStore.get().chats.length)current=aiStore.get().chats[0].id;renderList();renderChat();
}
