import {aiStore} from '../ai/store.js';
import {providerCatalog} from '../ai/providers.js';
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
export function aiPage(){const st=aiStore.get();return `<div class="page ai-page"><div class="page-title"><div><h2>AI</h2><p>A real chat shell that can call a user-configured endpoint. No fake assistant messages are generated.</p></div><span class="code-pill">${st.chats.length} CHATS</span></div><div class="ai-layout"><aside class="glass ai-sidebar"><div class="section-top"><h3>Conversations</h3><button class="icon-btn" id="new-chat">+</button></div><div id="chat-list" class="chat-list"></div><div class="ai-sidebar-footer"><label class="muted">Agent<select id="agent-select"><option>General Assistant</option><option>Coding Agent</option><option>Research Agent</option><option>Creative Agent</option><option>Debugging Agent</option><option>Custom</option></select></label></div></aside><section class="glass ai-main"><div class="ai-toolbar"><div><b id="ai-title">New chat</b><span class="muted" id="ai-provider-label">${esc(providerCatalog[st.provider]?.name||st.provider)} · ${esc(st.model||'model not configured')}</span></div><div class="toolbar-actions"><button class="ghost-btn" id="rename-chat">RENAME</button><button class="ghost-btn" id="clear-chat">CLEAR</button><button class="danger-btn" id="delete-chat">DELETE</button></div></div><div id="chat-messages" class="chat-messages"></div><div class="chat-compose"><input id="file-attach" type="file" hidden><button class="ghost-btn" id="attach-file">ATTACH</button><textarea id="chat-input" rows="2" placeholder="Message the selected provider…"></textarea><button class="primary-btn" id="send-chat">SEND</button></div></section><section class="glass section-card ai-config"><div class="section-top"><h3>Provider Configuration</h3><span class="code-pill">USER CONTROLLED</span></div><div class="control-grid"><div class="control"><label>Provider</label><select id="provider-select">${Object.entries(providerCatalog).map(([id,p])=>`<option value="${id}" ${st.provider===id?'selected':''}>${p.name}</option>`).join('')}</select></div><div class="control"><label>Model</label><input id="provider-model" value="${esc(st.model)}" placeholder="model identifier"></div><div class="control"><label>Endpoint</label><input id="provider-endpoint" value="${esc(st.endpoint)}" placeholder="https://…/chat/completions"><small>For GitHub Pages, use a CORS-enabled endpoint or your own backend proxy.</small></div><div class="control"><label>API key</label><input id="provider-key" type="password" value="${esc(st.apiKey)}" placeholder="Stored only in this browser"><small>Never hard-code this into the repository. This value is local browser storage.</small></div></div><div class="notice">Direct browser calls can fail because of provider CORS rules. That is a real browser restriction; if it happens, point Endpoint at a backend you control.</div></section></div></div>`}

export function bindAI({toast}={}){
 const root=document.querySelector('.ai-page');if(!root)return;let current=aiStore.get().chats[0]?.id||null;
 const list=root.querySelector('#chat-list'),messages=root.querySelector('#chat-messages');
 function ensureChat(){let chat=aiStore.get().chats.find(c=>c.id===current);if(!chat){chat={id:crypto.randomUUID(),title:'New chat',createdAt:new Date().toISOString(),messages:[]};aiStore.addChat(chat);current=chat.id}return chat}
 function renderList(){const chats=aiStore.get().chats;list.innerHTML=chats.length?chats.map(c=>`<button class="chat-row ${c.id===current?'active':''}" data-chat="${c.id}"><span>${esc(c.title)}</span><small>${c.messages.length}</small></button>`).join(''):'<div class="empty">No saved chats</div>';list.querySelectorAll('[data-chat]').forEach(b=>b.addEventListener('click',()=>{current=b.dataset.chat;renderChat()}))}
 function renderChat(){const chat=aiStore.get().chats.find(c=>c.id===current);root.querySelector('#ai-title').textContent=chat?.title||'New chat';messages.innerHTML=chat?.messages.length?chat.messages.map(m=>`<div class="chat-message ${m.role}"><div class="chat-role">${m.role.toUpperCase()}</div><div class="chat-bubble">${esc(m.content)}</div></div>`).join(''):'<div class="empty"><strong>Ready</strong><span>Configure a provider, then send a message. Requests and replies are saved locally.</span></div>';messages.scrollTop=messages.scrollHeight}
 root.querySelector('#new-chat')?.addEventListener('click',()=>{const c={id:crypto.randomUUID(),title:'New chat',createdAt:new Date().toISOString(),messages:[]};aiStore.addChat(c);current=c.id;renderList();renderChat()});
 root.querySelector('#rename-chat')?.addEventListener('click',()=>{const c=ensureChat(),name=prompt('Chat name',c.title);if(name?.trim()){c.title=name.trim();aiStore.updateChats(aiStore.get().chats);renderList();renderChat()}});
 root.querySelector('#clear-chat')?.addEventListener('click',()=>{const c=ensureChat();c.messages=[];aiStore.updateChats(aiStore.get().chats);renderChat()});
 root.querySelector('#delete-chat')?.addEventListener('click',()=>{if(!current)return;aiStore.updateChats(aiStore.get().chats.filter(c=>c.id!==current));current=aiStore.get().chats[0]?.id||null;renderList();renderChat()});
 root.querySelector('#provider-select')?.addEventListener('change',e=>{aiStore.set({provider:e.target.value});updateLabel()});
 root.querySelector('#provider-model')?.addEventListener('change',e=>{aiStore.set({model:e.target.value});updateLabel()});
 root.querySelector('#provider-endpoint')?.addEventListener('change',e=>aiStore.set({endpoint:e.target.value.trim()}));
 root.querySelector('#provider-key')?.addEventListener('change',e=>aiStore.set({apiKey:e.target.value}));
 root.querySelector('#agent-select')?.addEventListener('change',e=>aiStore.set({agent:e.target.value}));
 root.querySelector('#attach-file')?.addEventListener('click',()=>root.querySelector('#file-attach')?.click());
 root.querySelector('#file-attach')?.addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;const text=await f.text().catch(()=>null);const input=root.querySelector('#chat-input');if(text!==null)input.value+=(input.value?'\n\n':'')+`[Attached file: ${f.name}]\n${text.slice(0,12000)}`;else input.value+=(input.value?'\n\n':'')+`[Attached file: ${f.name}; binary content is not embedded]`;toast?.(`Attached ${f.name}`)});
 root.querySelector('#send-chat')?.addEventListener('click',async()=>{const input=root.querySelector('#chat-input'),content=input.value.trim();if(!content)return;const cfg=aiStore.get();if(!cfg.endpoint||!cfg.model||!cfg.apiKey){messages.insertAdjacentHTML('beforeend','<div class="chat-message system"><div class="chat-role">SYSTEM</div><div class="chat-bubble">Provider is not configured. Enter an endpoint, model and API key. No network request was sent.</div></div>');return}const chat=ensureChat();chat.messages.push({role:'user',content,at:new Date().toISOString()});chat.title=chat.title==='New chat'?content.slice(0,32):chat.title;aiStore.updateChats(aiStore.get().chats);input.value='';renderList();renderChat();const send=root.querySelector('#send-chat');send.disabled=true;send.textContent='…';try{const provider=providerCatalog[cfg.provider].factory(cfg);const reply=await provider.send(chat.messages.map(m=>({role:m.role,content:m.content})));chat.messages.push({role:'assistant',content:reply,at:new Date().toISOString()});aiStore.updateChats(aiStore.get().chats);renderChat()}catch(err){messages.insertAdjacentHTML('beforeend',`<div class="chat-message system"><div class="chat-role">ERROR</div><div class="chat-bubble">${esc(err.message||String(err))}</div></div>`)}finally{send.disabled=false;send.textContent='SEND'}});
 function updateLabel(){const s=aiStore.get();root.querySelector('#ai-provider-label').textContent=`${providerCatalog[s.provider].name} · ${s.model||'model not configured'}`}
 renderList();renderChat();root.querySelector('#agent-select').value=aiStore.get().agent||'General Assistant';
}
