export function simplePage(kind){
const cfg={
 proxy:['Proxy','Optional helper boundary.','Configure and observe a companion proxy service from this UI.','A static webpage cannot become a system-wide proxy by itself. This module is designed to pair with a local helper or backend service.'],
 phone:['Phone','Companion connection boundary.','Pair a supported companion application and show transport/device status here.','Unrestricted phone control requires browser-supported protocols, explicit permissions, or a companion application.'],
 spoof:['Spoof','Tab appearance tools.','Change the document title, favicon, startup screen, and legitimate SPA route state.','JavaScript cannot arbitrarily rewrite the real browser address bar URL.']
}[kind];
return `<div class="page"><div class="page-title"><div><h2>${cfg[0]}</h2><p>${cfg[1]}</p></div><span class="code-pill">BOUNDARY</span></div><div class="section-grid"><section class="glass section-card"><h3>Module surface</h3><div class="empty" style="margin-top:14px"><div class="empty-icon">◈</div><strong>${cfg[2]}</strong><span>This is an extension surface for the matching companion/backend, not a simulated connection.</span></div></section><section class="glass section-card"><h3>Capability boundary</h3><div class="notice" style="margin-top:14px">${cfg[3]}</div></section></div>${kind==='spoof'?`<section class="glass section-card" style="margin-top:14px"><div class="section-top"><h3>Tab appearance</h3><span class="muted">local</span></div><div class="control-grid"><div class="control"><label>Page title</label><input id="spoof-title" type="text" value="${document.title.replace(/"/g,'&quot;')}"></div><div class="control"><label>Application path</label><input id="spoof-path" type="text" value="${location.hash||'#home'}"></div></div><div class="hero-actions"><button class="primary-btn" id="spoof-apply">APPLY</button><button class="ghost-btn" id="spoof-reset">RESET</button></div></section>`:''}</div>`
}
export function bindSimple(kind,{toast}){
 if(kind!=='spoof')return;document.querySelector('#spoof-apply')?.addEventListener('click',()=>{const title=document.querySelector('#spoof-title').value.trim();if(title){document.title=title}const path=document.querySelector('#spoof-path').value.trim();if(path.startsWith('#'))history.replaceState({},'',path);toast('Tab appearance updated')});document.querySelector('#spoof-reset')?.addEventListener('click',()=>{document.title='NEXUS // Personal Web OS';history.replaceState({},'','#home');toast('Tab appearance reset')});
}
