import {store} from '../core/store.js';
import {getUtilities,toggleUtility,updateKeybind,getKeybind} from '../utilities/registry.js';

function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
export function utilitiesPage(){
 const st=store.get();
 return `<div class="page utilities-page"><div class="page-title"><div><h2>Utilities</h2><p>Actual controls for overlays, effects and local utilities.</p></div><span class="code-pill">${getUtilities().filter(x=>x.enabled).length} ACTIVE</span></div><div class="utility-layout"><section class="glass section-card"><div class="section-top"><h3>Live Registry</h3><span class="muted">Changes apply immediately</span></div><div class="utility-table">${getUtilities().map(u=>`<div class="utility-item ${u.enabled?'enabled':''}"><div><div class="utility-name">${esc(u.name)}</div><div class="utility-meta">${u.category} · ${u.enabled?'RUNNING':'IDLE'}</div></div><div class="utility-actions"><input class="keybind-input" data-bind="${u.id}" value="${esc(getKeybind(u.id))}" placeholder="KEY"><button class="switch ${u.enabled?'on':''}" data-util="${u.id}"></button></div></div>`).join('')}</div></section><section class="glass section-card"><div class="section-top"><h3>HUD Editor</h3><span class="code-pill">LIVE</span></div><p class="muted">Enable an overlay, then drag it directly on the screen. Position, scale, opacity and visibility persist.</p><div class="mini-preview"><div class="preview-chip">FPS</div><div class="preview-chip">CPS</div><div class="preview-chip">W A S D</div></div><button class="primary-btn" id="open-hud-settings">OPEN HUD SETTINGS</button><div class="notice" style="margin-top:12px">The HUD is not a mockup: FPS measures requestAnimationFrame pacing, CPS reads real pointer input, and Keystrokes reads actual keyboard events.</div></section><section class="glass section-card"><div class="section-top"><h3>Local Autoclicker</h3><span class="code-pill">PAGE ONLY</span></div><div class="notice">This can dispatch synthetic clicks inside this webpage. Browser security prevents it from becoming a trusted system-wide mouse driver.</div><div class="control-grid"><div class="control"><label>CPS <span id="auto-cps-value">${st.autoclicker.cps}</span></label><input id="auto-cps" type="range" min="1" max="30" value="${st.autoclicker.cps}"></div><div class="control"><label>Mode</label><select id="auto-mode"><option value="hold" ${st.autoclicker.mode==='hold'?'selected':''}>Hold / pointer active</option><option value="toggle" ${st.autoclicker.mode==='toggle'?'selected':''}>Toggle</option></select></div></div><button class="${st.autoclicker.enabled?'danger-btn':'primary-btn'}" id="auto-toggle">${st.autoclicker.enabled?'STOP AUTOCLICKER':'START AUTOCLICKER'}</button></section></div></div>`;
}
export function bindUtilities({toast,openSettings}){
 const root=document.querySelector('.utilities-page');if(!root)return;
 root.querySelectorAll('[data-util]').forEach(b=>b.addEventListener('click',()=>{const next=toggleUtility(b.dataset.util);document.dispatchEvent(new CustomEvent('nexus:hud-change'));toast(`${b.dataset.util}: ${next?'ON':'OFF'}`);renderUtilitiesOnly()}));
 root.querySelectorAll('[data-bind]').forEach(input=>input.addEventListener('change',e=>{updateKeybind(e.target.dataset.bind,e.target.value.trim());toast(`Keybind saved: ${e.target.value.trim()||'none'}`)}));
 root.querySelector('#open-hud-settings')?.addEventListener('click',()=>openSettings('hud'));
 root.querySelector('#auto-cps')?.addEventListener('input',e=>{store.set({autoclicker:{...store.get().autoclicker,cps:+e.target.value}});root.querySelector('#auto-cps-value').textContent=e.target.value});
 root.querySelector('#auto-mode')?.addEventListener('change',e=>store.set({autoclicker:{...store.get().autoclicker,mode:e.target.value}}));
 root.querySelector('#auto-toggle')?.addEventListener('click',()=>{const on=!store.get().autoclicker.enabled;document.dispatchEvent(new CustomEvent('nexus:autoclicker',{detail:{action:on?'start':'stop'}}));toast(`Autoclicker ${on?'started':'stopped'}`);renderUtilitiesOnly()});
 function renderUtilitiesOnly(){const page=document.querySelector('.utilities-page');if(!page)return;const active=getUtilities().filter(x=>x.enabled).length;const badge=document.querySelector('.utilities-page .page-title .code-pill');if(badge)badge.textContent=`${active} ACTIVE`;getUtilities().forEach(u=>{const row=page.querySelector(`[data-util="${u.id}"]`)?.closest('.utility-item');if(row){row.classList.toggle('enabled',u.enabled);row.querySelector('.switch')?.classList.toggle('on',u.enabled);row.querySelector('.utility-meta').textContent=`${u.category} · ${u.enabled?'RUNNING':'IDLE'}`}})}
}
